# Deploy to Vercel Preview
---
name: Vercel.Preview

on:
  push:
    branches: [ "advanture-test", "dev*/**" ]
  pull_request:
    branches: [ "advanture-test" ]

  # Allows to run workflow manually
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  # Vercel Preview Deployment
  # https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
  Vercel-Deploy-Preview:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT || 'development' }}
    strategy:
      matrix:
        pnpm-version: ${{ fromJSON(vars.PNPM_VERSION || '[ "9" ]') }}
        node-version: ${{ fromJSON(vars.NODE_VERSION || '[ "20" ]') }}
        vercel-version: ${{ fromJSON(vars.VERCEL_VERSION || '[ "37.4.2" ]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Install Vercel CLI
        run: npm install --global vercel@${{ matrix.vercel-version }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
